version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    tty: true
    volumes:
      - ./apps/backend/src:/api/src
    ports:
      - "3000:3000"
  frontend:
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    volumes:
      - ./apps/frontend/src:/app/src
      - ./apps/frontend/public:/app/public
    ports:
      - "3100:3100"